project:
  type: website
  output-dir: docs

website:
  title: "<a href='about.html' class='navbar-brand-link'>Rimlan Alva</a>"
  navbar:
    background: "#121212"
    foreground: "#f5f5f5"
    left:
      - text: "Projects"
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/rimaln
        aria-label: "GitHub"
      - icon: linkedin
        href: https://www.linkedin.com/in/rimlan-alva-149581282/
        aria-label: "LinkedIn"
      - icon: envelope
        href: mailto:ralv0004@student.monash.edu
        aria-label: "Email"

format:
  html:
    theme:
      dark: cyborg
    css: styles.css
    toc: true
